# Generated by Django 5.0.9 on 2024-11-20 19:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients_management', '0003_alter_client_city_alter_unit_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientOperation',
            fields=[
                ('client_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='clients_management.client')),
                ('operation_type', models.CharField(choices=[('A', 'Adicionar'), ('E', 'Editar'), ('D', 'Deletar')], max_length=1, verbose_name='Tipo de Operação')),
                ('operation_status', models.CharField(choices=[('A', 'Em Análise'), ('AC', 'Aceito'), ('R', 'Rejeitado')], default='A', max_length=2, verbose_name='Status da Operação')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comments', models.TextField(blank=True, help_text='Feedback do Gerente Prophy e Físico Médico Interno.', null=True, verbose_name='Comentários')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_operations', to='clients_management.client', verbose_name='Cliente')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_operations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Operação em Cliente',
                'verbose_name_plural': 'Operações em Clientes',
            },
            bases=('clients_management.client', models.Model),
        ),
        migrations.CreateModel(
            name='EquipmentOperation',
            fields=[
                ('equipment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='clients_management.equipment')),
                ('operation_type', models.CharField(choices=[('A', 'Adicionar'), ('E', 'Editar'), ('D', 'Deletar')], max_length=1, verbose_name='Tipo de Operação')),
                ('operation_status', models.CharField(choices=[('A', 'Em Análise'), ('AC', 'Aceito'), ('R', 'Rejeitado')], default='A', max_length=2, verbose_name='Status da Operação')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comments', models.TextField(blank=True, help_text='Feedback do Gerente Prophy e Físico Médico Interno.', null=True, verbose_name='Comentários')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_operations', to=settings.AUTH_USER_MODEL)),
                ('equipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equipment_operations', to='clients_management.equipment')),
            ],
            options={
                'verbose_name': 'Operação de Equipamento',
                'verbose_name_plural': 'Operações de Equipamentos',
            },
            bases=('clients_management.equipment', models.Model),
        ),
        migrations.CreateModel(
            name='UnitOperation',
            fields=[
                ('unit_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='clients_management.unit')),
                ('operation_type', models.CharField(choices=[('A', 'Adicionar'), ('E', 'Editar'), ('D', 'Deletar')], max_length=1, verbose_name='Tipo de Operação')),
                ('operation_status', models.CharField(choices=[('A', 'Em Análise'), ('AC', 'Aceito'), ('R', 'Rejeitado')], default='A', max_length=2, verbose_name='Status da Operação')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comments', models.TextField(blank=True, help_text='Feedback do Gerente Prophy e Físico Médico Interno.', null=True, verbose_name='Comentários')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_operations', to=settings.AUTH_USER_MODEL)),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unit_operations', to='clients_management.unit')),
            ],
            options={
                'verbose_name': 'Operação de Unidade',
                'verbose_name_plural': 'Operações de Unidades',
            },
            bases=('clients_management.unit', models.Model),
        ),
    ]
