# Generated by Django 5.0.11 on 2025-02-11 20:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientOperation',
            fields=[
                ('operation_type', models.CharField(choices=[('A', 'Adicionar'), ('E', 'Editar'), ('D', 'Deletar'), ('C', '-')], max_length=1, verbose_name='Tipo de Operação')),
                ('operation_status', models.CharField(choices=[('REV', 'Em Análise'), ('A', 'Aceito'), ('R', 'Rejeitado')], default='REV', max_length=3, verbose_name='Status da Operação')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField(blank=True, help_text='Anotações para descrever a operação.', null=True, verbose_name='Nota')),
                ('client_ptr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='operation', serialize=False, to='clients_management.client')),
            ],
            options={
                'verbose_name': 'Operação de Cliente',
                'verbose_name_plural': 'Operações de Clientes',
            },
            bases=('clients_management.client', models.Model),
        ),
        migrations.CreateModel(
            name='EquipmentOperation',
            fields=[
                ('operation_type', models.CharField(choices=[('A', 'Adicionar'), ('E', 'Editar'), ('D', 'Deletar'), ('C', '-')], max_length=1, verbose_name='Tipo de Operação')),
                ('operation_status', models.CharField(choices=[('REV', 'Em Análise'), ('A', 'Aceito'), ('R', 'Rejeitado')], default='REV', max_length=3, verbose_name='Status da Operação')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField(blank=True, help_text='Anotações para descrever a operação.', null=True, verbose_name='Nota')),
                ('equipment_ptr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='operation', serialize=False, to='clients_management.equipment')),
            ],
            options={
                'verbose_name': 'Operação de Equipamento',
                'verbose_name_plural': 'Operações de Equipamentos',
            },
            bases=('clients_management.equipment', models.Model),
        ),
        migrations.CreateModel(
            name='UnitOperation',
            fields=[
                ('operation_type', models.CharField(choices=[('A', 'Adicionar'), ('E', 'Editar'), ('D', 'Deletar'), ('C', '-')], max_length=1, verbose_name='Tipo de Operação')),
                ('operation_status', models.CharField(choices=[('REV', 'Em Análise'), ('A', 'Aceito'), ('R', 'Rejeitado')], default='REV', max_length=3, verbose_name='Status da Operação')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField(blank=True, help_text='Anotações para descrever a operação.', null=True, verbose_name='Nota')),
                ('unit_ptr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='operation', serialize=False, to='clients_management.unit')),
            ],
            options={
                'verbose_name': 'Operação de Unidade',
                'verbose_name_plural': 'Operações de Unidades',
            },
            bases=('clients_management.unit', models.Model),
        ),
    ]
