# Generated by Django 5.0.10 on 2024-12-17 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisitions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientoperation',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='equipmentoperation',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='unitoperation',
            name='comments',
        ),
        migrations.AddField(
            model_name='clientoperation',
            name='note',
            field=models.TextField(blank=True, help_text='Anotações para descrever a operação.', null=True, verbose_name='Nota'),
        ),
        migrations.AddField(
            model_name='equipmentoperation',
            name='note',
            field=models.TextField(blank=True, help_text='Anotações para descrever a operação.', null=True, verbose_name='Nota'),
        ),
        migrations.AddField(
            model_name='unitoperation',
            name='note',
            field=models.TextField(blank=True, help_text='Anotações para descrever a operação.', null=True, verbose_name='Nota'),
        ),
    ]
