# Generated by Django 5.0.9 on 2024-11-23 14:59

import django.db.models.deletion
import requisitions.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients_management', '0004_remove_client_status_client_active_alter_client_cnpj'),
        ('requisitions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientoperation',
            options={'verbose_name': 'Operação de Cliente', 'verbose_name_plural': 'Operações de Clientes'},
        ),
        migrations.RenameField(
            model_name='equipmentoperation',
            old_name='equipment',
            new_name='original_equipment',
        ),
        migrations.RenameField(
            model_name='unitoperation',
            old_name='unit',
            new_name='original_unit',
        ),
        migrations.RemoveField(
            model_name='clientoperation',
            name='client',
        ),
        migrations.AddField(
            model_name='clientoperation',
            name='original_client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='client_operations', to='clients_management.client', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='clientoperation',
            name='operation_status',
            field=models.CharField(choices=[(requisitions.models.OperationStatus['REVIEW'], 'Em Análise'), (requisitions.models.OperationStatus['ACCEPTED'], 'Aceito'), (requisitions.models.OperationStatus['REJECTED'], 'Rejeitado')], default=requisitions.models.OperationStatus['REVIEW'], max_length=8, verbose_name='Status da Operação'),
        ),
        migrations.AlterField(
            model_name='clientoperation',
            name='operation_type',
            field=models.CharField(choices=[(requisitions.models.OperationType['ADD'], 'Adicionar'), (requisitions.models.OperationType['EDIT'], 'Editar'), (requisitions.models.OperationType['DELETE'], 'Deletar')], max_length=6, verbose_name='Tipo de Operação'),
        ),
        migrations.AlterField(
            model_name='equipmentoperation',
            name='operation_status',
            field=models.CharField(choices=[(requisitions.models.OperationStatus['REVIEW'], 'Em Análise'), (requisitions.models.OperationStatus['ACCEPTED'], 'Aceito'), (requisitions.models.OperationStatus['REJECTED'], 'Rejeitado')], default=requisitions.models.OperationStatus['REVIEW'], max_length=8, verbose_name='Status da Operação'),
        ),
        migrations.AlterField(
            model_name='equipmentoperation',
            name='operation_type',
            field=models.CharField(choices=[(requisitions.models.OperationType['ADD'], 'Adicionar'), (requisitions.models.OperationType['EDIT'], 'Editar'), (requisitions.models.OperationType['DELETE'], 'Deletar')], max_length=6, verbose_name='Tipo de Operação'),
        ),
        migrations.AlterField(
            model_name='unitoperation',
            name='operation_status',
            field=models.CharField(choices=[(requisitions.models.OperationStatus['REVIEW'], 'Em Análise'), (requisitions.models.OperationStatus['ACCEPTED'], 'Aceito'), (requisitions.models.OperationStatus['REJECTED'], 'Rejeitado')], default=requisitions.models.OperationStatus['REVIEW'], max_length=8, verbose_name='Status da Operação'),
        ),
        migrations.AlterField(
            model_name='unitoperation',
            name='operation_type',
            field=models.CharField(choices=[(requisitions.models.OperationType['ADD'], 'Adicionar'), (requisitions.models.OperationType['EDIT'], 'Editar'), (requisitions.models.OperationType['DELETE'], 'Deletar')], max_length=6, verbose_name='Tipo de Operação'),
        ),
    ]
