# Generated by Django 5.0.9 on 2024-11-23 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisitions', '0002_alter_clientoperation_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientoperation',
            name='operation_status',
            field=models.CharField(choices=[('REV', 'Em Análise'), ('A', 'Aceito'), ('R', 'Rejeitado')], default='REV', max_length=3, verbose_name='Status da Operação'),
        ),
        migrations.AlterField(
            model_name='clientoperation',
            name='operation_type',
            field=models.CharField(choices=[('A', 'Adicionar'), ('E', 'Editar'), ('D', 'Deletar')], max_length=1, verbose_name='Tipo de Operação'),
        ),
        migrations.AlterField(
            model_name='equipmentoperation',
            name='operation_status',
            field=models.CharField(choices=[('REV', 'Em Análise'), ('A', 'Aceito'), ('R', 'Rejeitado')], default='REV', max_length=3, verbose_name='Status da Operação'),
        ),
        migrations.AlterField(
            model_name='equipmentoperation',
            name='operation_type',
            field=models.CharField(choices=[('A', 'Adicionar'), ('E', 'Editar'), ('D', 'Deletar')], max_length=1, verbose_name='Tipo de Operação'),
        ),
        migrations.AlterField(
            model_name='unitoperation',
            name='operation_status',
            field=models.CharField(choices=[('REV', 'Em Análise'), ('A', 'Aceito'), ('R', 'Rejeitado')], default='REV', max_length=3, verbose_name='Status da Operação'),
        ),
        migrations.AlterField(
            model_name='unitoperation',
            name='operation_type',
            field=models.CharField(choices=[('A', 'Adicionar'), ('E', 'Editar'), ('D', 'Deletar')], max_length=1, verbose_name='Tipo de Operação'),
        ),
    ]
