# Generated by Django 5.0.9 on 2024-11-23 18:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients_management', '0005_alter_client_address_alter_unit_address'),
        ('requisitions', '0003_alter_clientoperation_operation_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientoperation',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_operations', to=settings.AUTH_USER_MODEL, verbose_name='Criado por'),
        ),
        migrations.AlterField(
            model_name='clientoperation',
            name='original_client',
            field=models.ForeignKey(blank=True, help_text='Cliente original associado à operação.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='client_operations', to='clients_management.client', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='equipmentoperation',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_operations', to=settings.AUTH_USER_MODEL, verbose_name='Criado por'),
        ),
        migrations.AlterField(
            model_name='equipmentoperation',
            name='original_equipment',
            field=models.ForeignKey(blank=True, help_text='Equipamento original associado à operação.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equipment_operations', to='clients_management.equipment', verbose_name='Equipamento'),
        ),
        migrations.AlterField(
            model_name='unitoperation',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_operations', to=settings.AUTH_USER_MODEL, verbose_name='Criado por'),
        ),
        migrations.AlterField(
            model_name='unitoperation',
            name='original_unit',
            field=models.ForeignKey(blank=True, help_text='Unidade original associada à operação.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unit_operations', to='clients_management.unit', verbose_name='Unidade'),
        ),
    ]
