# Generated by Django 5.0.9 on 2024-11-26 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients_management', '0005_alter_client_address_alter_unit_address'),
        ('requisitions', '0004_alter_clientoperation_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientoperation',
            name='client_ptr',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='operation', serialize=False, to='clients_management.client'),
        ),
        migrations.AlterField(
            model_name='clientoperation',
            name='original_client',
            field=models.ForeignKey(blank=True, help_text='Cliente original associado à operação.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='new_operations', to='clients_management.client', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='equipmentoperation',
            name='equipment_ptr',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='operation', serialize=False, to='clients_management.equipment'),
        ),
        migrations.AlterField(
            model_name='equipmentoperation',
            name='original_equipment',
            field=models.ForeignKey(blank=True, help_text='Equipamento original associado à operação.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='new_operations', to='clients_management.equipment', verbose_name='Equipamento'),
        ),
        migrations.AlterField(
            model_name='unitoperation',
            name='original_unit',
            field=models.ForeignKey(blank=True, help_text='Unidade original associada à operação.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='new_operations', to='clients_management.unit', verbose_name='Unidade'),
        ),
        migrations.AlterField(
            model_name='unitoperation',
            name='unit_ptr',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='operation', serialize=False, to='clients_management.unit'),
        ),
    ]
