# Generated by Django 5.0.11 on 2025-02-22 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients_management', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='units', to='clients_management.client', verbose_name='Cliente'),
        ),
    ]
