# Generated by Django 5.0.9 on 2024-11-20 19:09

import core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients_management', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='city',
            field=models.CharField(max_length=50, validators=[core.validators.AlphaOnly()], verbose_name='Cidade da instituição'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unit', to=settings.AUTH_USER_MODEL, verbose_name='Gerente de Unidade'),
        ),
    ]
