# Generated by Django 5.1.10 on 2025-08-09 21:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients_management', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=50, verbose_name='Assunto')),
                ('activities', models.TextField(verbose_name='Atividades')),
            ],
        ),
        migrations.AlterField(
            model_name='proposal',
            name='contract_type',
            field=models.CharField(choices=[('A', 'Anual'), ('M', 'Mensal'), ('W', 'Semanal')], max_length=1, verbose_name='Tipo de contrato'),
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completion_date', models.DateField(verbose_name='Data realizado')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Data de vencimento')),
                ('file', models.FileField(upload_to='reports/', verbose_name='Arquivo')),
                ('report_type', models.CharField(choices=[('CQ', 'Controle de Qualidade'), ('CQM', 'Controle de Qualidade de Monitores'), ('TE', 'Teste de EPI'), ('LR', 'Levantamento Radiométrico e Fuga de Cabeçote'), ('M', 'Memorial'), ('TR', 'Treinamento de Radioproteção'), ('TSR', 'Treinamento de Segurança em Ressonância Magnética'), ('AD', 'Ato de designação'), ('ID', 'Investigação de dose'), ('POP', 'POP'), ('O', 'Outros')], max_length=3, verbose_name='Tipo')),
                ('equipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='clients_management.equipment', verbose_name='Equipamento')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='clients_management.unit', verbose_name='Unidade')),
            ],
            options={
                'verbose_name': 'Relatório',
                'verbose_name_plural': 'Relatórios',
                'ordering': ['-completion_date'],
            },
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Data')),
                ('status', models.CharField(choices=[('P', 'Pendente'), ('C', 'Confirmado'), ('F', 'Realizado'), ('U', 'Não realizado')], default='P', max_length=1, verbose_name='Status')),
                ('contact_phone', models.CharField(max_length=13, verbose_name='Telefone do contato')),
                ('contact_name', models.CharField(max_length=50, verbose_name='Nome do contato')),
                ('service_order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='visit', to='clients_management.serviceorder', verbose_name='Ordem de Serviço')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='clients_management.unit', verbose_name='Unidade')),
            ],
            options={
                'verbose_name': 'Visita',
                'verbose_name_plural': 'Visitas',
            },
        ),
    ]
