# Generated by Django 5.0.9 on 2024-11-23 14:59

import clients_management.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients_management', '0003_alter_client_city_alter_unit_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='status',
        ),
        migrations.AddField(
            model_name='client',
            name='active',
            field=models.BooleanField(default=False, verbose_name='Ativo'),
        ),
        migrations.AlterField(
            model_name='client',
            name='cnpj',
            field=models.CharField(max_length=14, validators=[clients_management.validators.CNPJValidator()], verbose_name='CNPJ'),
        ),
    ]
