# Generated by Django 5.2.11 on 2026-02-16 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients_management', '0003_make_deleted_by_nullable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='equipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='clients_management.equipment', verbose_name='Equipamento'),
        ),
        migrations.AlterField(
            model_name='report',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='clients_management.unit', verbose_name='Unidade'),
        ),
    ]
