# Generated by Django 5.1.10 on 2025-08-23 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients_management', '0003_serviceorder_alter_proposal_contract_type_report_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceorder',
            name='activities',
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='conclusion',
            field=models.TextField(default='', help_text='A summary of the work performed and the resolution.', verbose_name='Conclusão'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='description',
            field=models.TextField(default='', help_text='A detailed description of the problem or service required.', verbose_name='Descrição'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='equipments',
            field=models.ManyToManyField(related_name='service_orders', to='clients_management.equipment'),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='subject',
            field=models.CharField(help_text="A brief, clear summary of the service order's purpose.", max_length=50, verbose_name='Assunto'),
        ),
    ]
