# Generated by Django 5.2.14 on 2026-05-23 18:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_responsible_prophy(apps, schema_editor):
    ServiceOrder = apps.get_model("clients_management", "ServiceOrder")
    UserAccount = apps.get_model("users", "UserAccount")

    default_user = (
        UserAccount.objects.filter(role="GP").first()
        or UserAccount.objects.filter(is_staff=True).first()
    )
    if default_user is None:
        return

    ServiceOrder.objects.filter(
        responsible_prophy__isnull=True
    ).update(responsible_prophy=default_user)


class Migration(migrations.Migration):

    dependencies = [
        ('clients_management', '0004_alter_report_equipment_alter_report_unit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceorder',
            name='responsible_prophy',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='service_orders',
                to=settings.AUTH_USER_MODEL,
                verbose_name='Responsável Prophy',
            ),
        ),
        migrations.RunPython(
            backfill_responsible_prophy,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='responsible_prophy',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='service_orders',
                to=settings.AUTH_USER_MODEL,
                verbose_name='Responsável Prophy',
            ),
        ),
    ]
