# Generated by Django 5.1.10 on 2025-09-13 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients_management', '0004_remove_serviceorder_activities_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='justification',
            field=models.TextField(default='', verbose_name='Justificativa'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='visit',
            name='status',
            field=models.CharField(choices=[('P', 'Pendente'), ('C', 'Confirmado'), ('F', 'Realizado'), ('U', 'Não realizado'), ('R', 'Reagendada')], default='P', max_length=1, verbose_name='Status'),
        ),
    ]
