# Generated by Django 5.0.10 on 2024-12-21 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients_management', '0005_alter_client_address_alter_unit_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='city',
            field=models.CharField(max_length=50, verbose_name='Cidade da instituição'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='city',
            field=models.CharField(blank=True, max_length=50, verbose_name='Cidade'),
        ),
    ]
