# Generated by Django 5.1.10 on 2025-09-14 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients_management', '0005_visit_justification_alter_visit_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='justification',
            field=models.TextField(blank=True, null=True, verbose_name='Justificativa'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='service_order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visit', to='clients_management.serviceorder', verbose_name='Ordem de Serviço'),
        ),
    ]
