# Generated by Django 5.1.10 on 2025-09-28 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients_management', '0006_alter_visit_justification_alter_visit_service_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceorder',
            name='updates',
            field=models.TextField(blank=True, null=True, verbose_name='Atualização'),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='conclusion',
            field=models.TextField(verbose_name='Conclusão'),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='description',
            field=models.TextField(verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='subject',
            field=models.CharField(max_length=50, verbose_name='Assunto'),
        ),
    ]
