# Generated by Django 5.2.15 on 2026-06-14 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients_management', '0006_seed_modalities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='report_type',
            field=models.CharField(choices=[('CQ', 'Controle de Qualidade'), ('CQM', 'Controle de Qualidade de Monitores'), ('TE', 'Teste de EPI'), ('LR', 'Levantamento Radiométrico e Fuga de Cabeçote'), ('M', 'Memorial'), ('MCDI', 'Memorial CDI'), ('MUS', 'Memorial US'), ('MRM', 'Memorial RM'), ('TR', 'Treinamento de Radioproteção'), ('TSR', 'Treinamento de Segurança em Ressonância Magnética'), ('AD', 'Ato de designação'), ('ID', 'Investigação de dose'), ('POP', 'POP'), ('O', 'Outros')], max_length=4, verbose_name='Tipo'),
        ),
    ]
