# Generated by Django 5.0.10 on 2025-01-18 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients_management', '0007_alter_equipment_equipment_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='equipment_photo',
            field=models.ImageField(blank=True, null=True, upload_to='equipments/photos', verbose_name='Foto do equipamento'),
        ),
    ]
