# Generated by Django 5.1.10 on 2025-10-12 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "clients_management",
            "0007_serviceorder_updates_alter_serviceorder_conclusion_and_more",
        ),
    ]

    operations = [
        # Rename the Visit model to Appointment
        migrations.RenameModel(
            old_name="Visit",
            new_name="Appointment",
        ),
        # Add the type field with default value
        migrations.AddField(
            model_name="appointment",
            name="type",
            field=models.CharField(
                choices=[("I", "Presencial"), ("O", "Online")],
                default="I",
                max_length=1,
                verbose_name="Tipo",
            ),
        ),
        # Update the related_name for service_order relationship
        migrations.AlterField(
            model_name="appointment",
            name="service_order",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="appointment",
                to="clients_management.serviceorder",
                verbose_name="Ordem de Serviço",
            ),
        ),
        # Update the related_name for unit relationship
        migrations.AlterField(
            model_name="appointment",
            name="unit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="appointments",
                to="clients_management.unit",
                verbose_name="Unidade",
            ),
        ),
        # Update model metadata
        migrations.AlterModelOptions(
            name="appointment",
            options={
                "verbose_name": "Agendamento",
                "verbose_name_plural": "Agendamentos",
            },
        ),
    ]
