# Generated by Django 5.1.10 on 2025-10-19 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients_management', '0008_rename_visit_to_appointment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='active',
            new_name='is_active',
        ),
    ]
