# Generated by Django 5.2.14

from django.db import migrations, models


def backfill_razao_social(apps, schema_editor):
    Client = apps.get_model("clients_management", "Client")
    Unit = apps.get_model("clients_management", "Unit")

    for model in (Client, Unit):
        for row in model.objects.filter(razao_social__isnull=True):
            row.razao_social = row.name
            row.save(update_fields=["razao_social"])


class Migration(migrations.Migration):

    dependencies = [
        ("clients_management", "0008_report_split_file_into_pdf_and_word"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="razao_social",
            field=models.CharField(
                max_length=150, null=True, verbose_name="Razão Social"
            ),
        ),
        migrations.AddField(
            model_name="unit",
            name="razao_social",
            field=models.CharField(
                max_length=150, null=True, verbose_name="Razão Social"
            ),
        ),
        migrations.RunPython(
            backfill_razao_social,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name="client",
            name="razao_social",
            field=models.CharField(max_length=150, verbose_name="Razão Social"),
        ),
        migrations.AlterField(
            model_name="unit",
            name="razao_social",
            field=models.CharField(max_length=150, verbose_name="Razão Social"),
        ),
    ]
