# Generated by Django 5.2.15 on 2026-07-11 17:27

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients_management', '0009_add_razao_social_to_client_and_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessory',
            name='equipment_photo',
            field=models.ImageField(upload_to='equipments/photos', validators=[core.validators.MaxFileSize(5)], verbose_name='Foto do equipamento'),
        ),
        migrations.AlterField(
            model_name='accessory',
            name='label_photo',
            field=models.ImageField(upload_to='equipments/labels', validators=[core.validators.MaxFileSize(5)], verbose_name='Foto da etiqueta'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='equipment_photo',
            field=models.ImageField(upload_to='equipments/photos', validators=[core.validators.MaxFileSize(5)], verbose_name='Foto do equipamento'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='label_photo',
            field=models.ImageField(upload_to='equipments/labels', validators=[core.validators.MaxFileSize(5)], verbose_name='Foto da etiqueta'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='pdf_version',
            field=models.FileField(upload_to='proposals/pdfs/', validators=[core.validators.MaxFileSize(10)]),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='word_version',
            field=models.FileField(upload_to='proposals/words/', validators=[core.validators.MaxFileSize(10)]),
        ),
        migrations.AlterField(
            model_name='report',
            name='pdf_file',
            field=models.FileField(upload_to='reports/pdfs/', validators=[core.validators.MaxFileSize(10)], verbose_name='Arquivo PDF'),
        ),
        migrations.AlterField(
            model_name='report',
            name='word_file',
            field=models.FileField(blank=True, upload_to='reports/words/', validators=[core.validators.MaxFileSize(10)], verbose_name='Arquivo Word'),
        ),
    ]
