# Generated by Django 5.1.14 on 2025-11-30 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients_management', '0009_rename_client_active_to_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='pdf_version',
            field=models.FileField(default='placeholders/default.jpg', upload_to='proposals/pdfs/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proposal',
            name='word_version',
            field=models.FileField(default='placeholders/default.jpg', upload_to='proposals/words/'),
            preserve_default=False,
        ),
    ]
