# Generated by Django 5.2.16 on 2026-08-01 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients_management', '0013_report_alter_description_required'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accessory',
            options={'ordering': ['model'], 'verbose_name': 'Acessório', 'verbose_name_plural': 'Acessórios'},
        ),
    ]
