# Generated by Django 5.0.7 on 2024-09-28 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacao', '0003_alter_useraccount_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='username',
        ),
        migrations.AddField(
            model_name='useraccount',
            name='cpf',
            field=models.CharField(default='0', max_length=11, unique=True, verbose_name='CPF'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='profile',
            field=models.CharField(choices=[('Físico Médico Interno', 'Físico Médico Interno'), ('Físico Médico Externo', 'Físico Médico Externo'), ('Gerente Prophy', 'Gerente Prophy'), ('Gerente Geral do Cliente', 'Gerente Geral do Cliente'), ('Gerente de Unidade', 'Gerente de Unidade'), ('Comercial', 'Comercial')], default='Gerente Geral do Cliente', max_length=30, verbose_name='Perfil'),
        ),
    ]
