# Generated by Django 5.0.8 on 2024-10-03 13:37

import autenticacao.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacao', '0006_alter_useraccount_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='cpf',
            field=models.CharField(max_length=11, unique=True, validators=[autenticacao.validators.CPFValidator()], verbose_name='CPF'),
        ),
    ]
