# Generated by Django 5.0.9 on 2024-10-12 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacao', '0008_alter_useraccount_is_active_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraccount',
            old_name='profile',
            new_name='role',
        ),
    ]
