# Generated by Django 5.1.10 on 2025-11-09 15:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InstitutionalMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Título')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('type', models.CharField(choices=[('PUB', 'Público'), ('INT', 'Interno')], max_length=3, verbose_name='Tipo')),
                ('category', models.CharField(choices=[('SIG', 'Sinalizações / Fluxogramas / Informativos'), ('IOE', 'Instruções Operacionais de Equipe'), ('TER', 'Termos'), ('POP', 'POPs'), ('LEG', 'Legislação Vigente'), ('GUI', 'Guias'), ('MAN', 'Manuais'), ('OUT', 'Outros'), ('IOE', 'Instruções Operacionais de Equipe'), ('POP', 'POPs'), ('GUI', 'Guias'), ('MAN', 'Manuais'), ('MRE', 'Modelos de Relatórios'), ('MDO', 'Modelos de Documentos'), ('IDV', 'Material Institucional de Identidade Visual'), ('OUT', 'Outros')], max_length=4, verbose_name='Categoria')),
                ('file', models.FileField(upload_to='materials/', verbose_name='Arquivo')),
                ('is_published', models.BooleanField(default=True, verbose_name='Publicado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('allowed_external_users', models.ManyToManyField(blank=True, limit_choices_to={'role': 'FME'}, related_name='institutional_materials_allowed', to=settings.AUTH_USER_MODEL, verbose_name='Externos com acesso')),
            ],
            options={
                'verbose_name': 'Material Institucional',
                'verbose_name_plural': 'Materiais Institucionais',
                'ordering': ['-created_at'],
            },
        ),
    ]
