# Generated by Django 5.2.9 on 2025-12-27 18:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('materials', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='institutionalmaterial',
            name='allowed_external_users',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role': 'FME'}, related_name='institutional_materials_allowed', to=settings.AUTH_USER_MODEL, verbose_name='Externos com acesso'),
        ),
    ]
