# Generated by Django 5.1.10 on 2025-11-09 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='institutionalmaterial',
            name='type',
        ),
        migrations.AddField(
            model_name='institutionalmaterial',
            name='visibility',
            field=models.CharField(choices=[('PUB', 'Público'), ('INT', 'Interno')], default='PUB', max_length=3, verbose_name='Visibilidade'),
            preserve_default=False,
        ),
    ]
