# Generated by Django 5.2.15 on 2026-07-11 17:27

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institutionalmaterial',
            name='file',
            field=models.FileField(upload_to='materials/', validators=[core.validators.MaxFileSize(10)], verbose_name='Arquivo'),
        ),
    ]
