# Generated by Django 5.1.10 on 2025-11-09 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0002_remove_institutionalmaterial_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='institutionalmaterial',
            name='is_published',
        ),
    ]
