# Generated by Django 5.1.10 on 2025-09-28 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='role',
            field=models.CharField(choices=[('FMI', 'Físico Médico Interno'), ('FME', 'Físico Médico Externo'), ('GP', 'Gerente Prophy'), ('GGC', 'Gerente Geral de Cliente'), ('GU', 'Gerente de Unidade'), ('C', 'Comercial'), ('SA', 'Conta de Serviço')], default='GGC', max_length=30, verbose_name='Perfil'),
        ),
    ]
