# Generated by Django 5.0.7 on 2024-09-23 17:49

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Proposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.CharField(max_length=14, unique=True, verbose_name='CNPJ')),
                ('cidade', models.CharField(max_length=50, verbose_name='Cidade da instituição')),
                ('estado', models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], max_length=2, verbose_name='Estado da instituição')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome do contato')),
                ('telefone', models.CharField(max_length=11, verbose_name='Telefone do contato')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail do contato')),
                ('data_proposta', models.DateField(default=datetime.date.today, verbose_name='Data da proposta')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor proposto')),
                ('tipo_contrato', models.CharField(choices=[('A', 'Anual'), ('M', 'Mensal')], max_length=1, verbose_name='Tipo de contrato')),
                ('status', models.CharField(choices=[('A', 'Aceito'), ('R', 'Rejeitado'), ('P', 'Pendente')], default='P', max_length=1)),
            ],
            options={
                'ordering': ['-data_proposta'],
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.CharField(max_length=14, unique=True, verbose_name='CNPJ')),
                ('nome_instituicao', models.CharField(max_length=50, verbose_name='Nome da instituição')),
                ('nome_contato', models.CharField(max_length=50, verbose_name='Nome do contato')),
                ('email_contato', models.EmailField(max_length=254, verbose_name='E-mail do contato')),
                ('email_instituicao', models.EmailField(max_length=254, verbose_name='E-mail da instituição')),
                ('telefone_instituicao', models.CharField(max_length=11, verbose_name='Telefone da instituição')),
                ('endereco_instituicao', models.CharField(max_length=50, verbose_name='Endereço da instituição')),
                ('estado_instituicao', models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], max_length=2, verbose_name='Estado da instituição')),
                ('cidade_instituicao', models.CharField(max_length=50, verbose_name='Cidade da instituição')),
                ('status', models.CharField(choices=[('A', 'Ativo'), ('I', 'Inativo')], default='A', max_length=1, verbose_name='Status')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Unidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome da unidade')),
                ('cnpj', models.CharField(max_length=14, unique=True, verbose_name='CNPJ da unidade')),
                ('nome_contato', models.CharField(max_length=50, verbose_name='Nome do contato')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail da unidade')),
                ('telefone', models.CharField(max_length=11, verbose_name='Telefone da unidade')),
                ('endereco', models.CharField(max_length=50, verbose_name='Endereço da unidade')),
                ('estado', models.CharField(blank=True, choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], max_length=2, verbose_name='Estado da unidade')),
                ('cidade', models.CharField(blank=True, max_length=50, verbose_name='Cidade da unidade')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unidades', to='gestao_clientes.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Equipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modalidade', models.CharField(max_length=50)),
                ('fabricante', models.CharField(max_length=30)),
                ('modelo', models.CharField(max_length=30)),
                ('numero_serie', models.CharField(blank=True, max_length=30, null=True, verbose_name='Número de Série')),
                ('registro_anvisa', models.CharField(blank=True, max_length=15, null=True, verbose_name='Registro na ANVISA')),
                ('foto_equipamento', models.ImageField(upload_to='equipamentos/fotos', verbose_name='Foto do equipamento')),
                ('foto_etiqueta', models.ImageField(blank=True, null=True, upload_to='equipamentos/etiquetas', verbose_name='Foto da etiqueta')),
                ('responsavel_manutencao', models.CharField(blank=True, max_length=50, null=True, verbose_name='Responsável pela manutenção')),
                ('email_responsavel', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail do responsável pela manutenção')),
                ('telefone_responsavel', models.CharField(blank=True, max_length=11, null=True, verbose_name='Telefone do responsável pela manutenção')),
                ('unidade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipamentos', to='gestao_clientes.unidade')),
            ],
        ),
    ]
