# Generated by Django 5.0.7 on 2024-08-23 17:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.CharField(max_length=14, unique=True, verbose_name='CNPJ')),
                ('nome_instituicao', models.CharField(max_length=50, verbose_name='Nome da instituição')),
                ('nome_contato', models.CharField(max_length=50, verbose_name='Nome do contato')),
                ('email_contato', models.EmailField(max_length=254, verbose_name='E-mail do contato')),
                ('email_instituicao', models.EmailField(max_length=254, verbose_name='E-mail da instituição')),
                ('telefone_instituicao', models.CharField(max_length=11, verbose_name='Telefone da instituição')),
                ('endereco_instituicao', models.TextField(verbose_name='Endereço da instituição')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clientes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Unidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome da unidade')),
                ('nome_contato', models.CharField(max_length=50, verbose_name='Nome do contato')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail da unidade')),
                ('telefone', models.CharField(max_length=11, verbose_name='Telefone da unidade')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unidades', to='gestao_clientes.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Equipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modalidade', models.CharField(max_length=50)),
                ('marca', models.CharField(max_length=30)),
                ('fabricante', models.CharField(max_length=30)),
                ('modelo', models.CharField(max_length=30)),
                ('numero_serie', models.CharField(max_length=30, unique=True, verbose_name='Número de Série')),
                ('registro_anvisa', models.CharField(max_length=15, unique=True, verbose_name='Registro na ANVISA')),
                ('foto_equipamento', models.ImageField(upload_to='equipamentos/fotos', verbose_name='Foto do equipamento')),
                ('foto_etiqueta', models.ImageField(blank=True, null=True, upload_to='equipamentos/etiquetas', verbose_name='Foto da etiqueta')),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipamentos', to='gestao_clientes.unidade')),
            ],
        ),
    ]
