# Generated by Django 5.0.7 on 2024-08-23 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_clientes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unidade',
            old_name='client',
            new_name='cliente',
        ),
    ]
