# Generated by Django 5.0.7 on 2024-09-28 18:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_clientes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='user',
        ),
        migrations.AddField(
            model_name='cliente',
            name='user',
            field=models.ManyToManyField(blank=True, related_name='clientes', to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
    ]
