# Generated by Django 5.0.7 on 2024-09-28 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_clientes', '0002_remove_cliente_user_cliente_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='user',
            new_name='users',
        ),
    ]
