# Generated by Django 5.0.7 on 2024-09-28 19:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_clientes', '0003_rename_user_cliente_users'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='endereco_instituicao',
            field=models.CharField(max_length=100, verbose_name='Endereço da instituição'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='clientes', to=settings.AUTH_USER_MODEL, verbose_name='Usuários'),
        ),
    ]
