# Generated by Django 5.0.7 on 2024-09-28 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_clientes', '0004_alter_cliente_endereco_instituicao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='telefone_instituicao',
            field=models.CharField(max_length=13, verbose_name='Telefone da instituição'),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='telefone_responsavel',
            field=models.CharField(blank=True, max_length=13, null=True, verbose_name='Telefone do responsável pela manutenção'),
        ),
        migrations.AlterField(
            model_name='proposta',
            name='telefone',
            field=models.CharField(max_length=13, verbose_name='Telefone do contato'),
        ),
        migrations.AlterField(
            model_name='unidade',
            name='endereco',
            field=models.CharField(max_length=100, verbose_name='Endereço da unidade'),
        ),
        migrations.AlterField(
            model_name='unidade',
            name='telefone',
            field=models.CharField(max_length=13, verbose_name='Telefone da unidade'),
        ),
    ]
