# Generated by Django 5.0.7 on 2024-08-23 19:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_clientes', '0004_alter_potencialcliente_data_proposta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='potencialcliente',
            name='data_proposta',
            field=models.DateField(default=datetime.date.today, verbose_name='Data da proposta'),
        ),
    ]
