# Generated by Django 5.0.7 on 2024-08-24 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_clientes', '0005_alter_potencialcliente_data_proposta'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='potencialcliente',
            options={'ordering': ['-data_proposta']},
        ),
    ]
