# Generated by Django 5.0.7 on 2024-08-31 14:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_clientes', '0006_alter_potencialcliente_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.CharField(max_length=14, unique=True, verbose_name='CNPJ')),
                ('cidade', models.CharField(max_length=50, verbose_name='Cidade da instituição')),
                ('estado', models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], max_length=2, verbose_name='Estado da instituição')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome do contato')),
                ('telefone', models.CharField(max_length=11, verbose_name='Telefone do contato')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail do contato')),
                ('data_proposta', models.DateField(default=datetime.date.today, verbose_name='Data da proposta')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor proposto')),
                ('tipo_contrato', models.CharField(choices=[('A', 'Anual'), ('M', 'Mensal')], max_length=1, verbose_name='Tipo de contrato')),
                ('status', models.CharField(choices=[('A', 'Aceito'), ('R', 'Rejeitado'), ('P', 'Pendente')], default='P', max_length=1)),
            ],
            options={
                'ordering': ['-data_proposta'],
            },
        ),
        migrations.DeleteModel(
            name='PotencialCliente',
        ),
        migrations.RemoveField(
            model_name='equipamento',
            name='marca',
        ),
        migrations.AddField(
            model_name='cliente',
            name='cidade_instituicao',
            field=models.CharField(blank=True, max_length=50, verbose_name='Cidade da instituição'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='estado_instituicao',
            field=models.CharField(blank=True, choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], max_length=2, verbose_name='Estado da instituição'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='status',
            field=models.CharField(choices=[('A', 'Ativo'), ('I', 'Inativo')], default='A', max_length=1, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='equipamento',
            name='email_responsavel',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail do responsável pela manutenção'),
        ),
        migrations.AddField(
            model_name='equipamento',
            name='responsavel_manutencao',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Responsável pela manutenção'),
        ),
        migrations.AddField(
            model_name='equipamento',
            name='telefone_responsavel',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='Telefone do responsável pela manutenção'),
        ),
        migrations.AddField(
            model_name='unidade',
            name='cidade',
            field=models.CharField(blank=True, max_length=50, verbose_name='Cidade da unidade'),
        ),
        migrations.AddField(
            model_name='unidade',
            name='cnpj',
            field=models.CharField(default=11111, max_length=14, unique=True, verbose_name='CNPJ da unidade'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unidade',
            name='endereco',
            field=models.CharField(default='a', max_length=50, verbose_name='Endereço da unidade'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unidade',
            name='estado',
            field=models.CharField(blank=True, choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], max_length=2, verbose_name='Estado da unidade'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='endereco_instituicao',
            field=models.CharField(max_length=50, verbose_name='Endereço da instituição'),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='numero_serie',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Número de Série'),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='registro_anvisa',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Registro na ANVISA'),
        ),
    ]
