# Generated by Django 5.0.8 on 2024-10-02 18:20

import gestao_clientes.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_clientes', '0007_alter_cliente_cnpj_alter_proposta_cnpj_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cnpj',
            field=models.CharField(max_length=14, unique=True, validators=[gestao_clientes.validators.FixedLength(14)], verbose_name='CNPJ'),
        ),
        migrations.AlterField(
            model_name='proposta',
            name='cnpj',
            field=models.CharField(max_length=14, validators=[gestao_clientes.validators.FixedLength(14)], verbose_name='CNPJ'),
        ),
        migrations.AlterField(
            model_name='unidade',
            name='cnpj',
            field=models.CharField(max_length=14, validators=[gestao_clientes.validators.FixedLength(14)], verbose_name='CNPJ'),
        ),
    ]
