# Generated by Django 5.0.8 on 2024-10-03 12:44

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_clientes', '0008_alter_cliente_cnpj_alter_proposta_cnpj_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='nome_contato',
            field=models.CharField(max_length=50, validators=[core.validators.AlphaOnly()], verbose_name='Nome do contato'),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='responsavel_manutencao',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[core.validators.AlphaOnly()], verbose_name='Responsável pela manutenção'),
        ),
        migrations.AlterField(
            model_name='proposta',
            name='cidade',
            field=models.CharField(max_length=50, validators=[core.validators.AlphaOnly()], verbose_name='Cidade da instituição'),
        ),
        migrations.AlterField(
            model_name='proposta',
            name='nome',
            field=models.CharField(max_length=50, validators=[core.validators.AlphaOnly()], verbose_name='Nome do contato'),
        ),
        migrations.AlterField(
            model_name='unidade',
            name='cidade',
            field=models.CharField(blank=True, max_length=50, validators=[core.validators.AlphaOnly()], verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='unidade',
            name='nome',
            field=models.CharField(max_length=50, validators=[core.validators.AlphaOnly()], verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='unidade',
            name='nome_contato',
            field=models.CharField(max_length=50, validators=[core.validators.AlphaOnly()], verbose_name='Nome do contato'),
        ),
    ]
