# Generated by Django 5.0.8 on 2024-10-03 13:58

import gestao_clientes.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_clientes', '0009_alter_cliente_nome_contato_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cnpj',
            field=models.CharField(max_length=14, unique=True, validators=[gestao_clientes.validators.CNPJValidator()], verbose_name='CNPJ'),
        ),
        migrations.AlterField(
            model_name='proposta',
            name='cnpj',
            field=models.CharField(max_length=14, validators=[gestao_clientes.validators.CNPJValidator()], verbose_name='CNPJ'),
        ),
        migrations.AlterField(
            model_name='unidade',
            name='cnpj',
            field=models.CharField(max_length=14, validators=[gestao_clientes.validators.CNPJValidator()], verbose_name='CNPJ'),
        ),
    ]
